version: '3.8'
services:
  maven:
    image: maven:latest
    links:
      - tomcat
      build:
        context: /root/boxfuse-sample-java-war-hello/
        dockerfile: Dockerfile
    volumes:
      - type: volume
        source: /tmp/
        target: /root/boxfuse-sample-java-war-hello